### ISSUE TITLE
Quadrotor does not move

### ISSUE THREAD

**Issue by pulver22** [vislab-tecnico-lisboa/ardrone_gazebo#4] opened 2017-03-18 18:34 UTC
We are using Ubuntu 16.04 with ROS Kinetic and Gazebo 7. We downloaded your workspace, compile it without issues and spawing world and quadrotor. We publish a message on /ardrone/takeoff but the robot is not moving in gazebo despite the fact that it is possible to read "Quadrotor takes off" in the console!
We tried also to send commands on /cmd_vel but, also in this case the UAV does not move from its position!

Do you have any idea of what is going on?

Cheers!

**Comment by nigno17** [comment] 2017-03-20 17:36
Hi, it was an issue with some changes that I did in order to use multiple drones for a project. I now fixed the bug. Now all drone topics are under the /quadrotor/ namespace. So you must publish an Empty message on the topic /quadrotor/ardrone/takeoff in order make it fly. Let me know if it solved your issue.

Ps: I didn't wrote the ardrone code, I just modified it in order to run it on gazebo 7 and ROS up to KINETIC and added it inside our lab world. The original Ardrone 2.0 was written by Hongrong Huang and Juergen Sturm of the Computer Vision Group at the Technical University of Munich (http://wiki.ros.org/tum_simulator).

**Comment by pulver22** [comment] 2017-03-20 18:16
Hi got the latest version of the repo and now it works! Thank you for fixing it! I checked the diff and I also was wondering about a namespace/topic_remapping issue that I was going to solve by myself!

The only point still unclear to me is the following. Why when I was sending a command to /ardrone/takeoff didn't it fly? It was supposed to do that and, in fact, in the gazebo console I could read "Quadrotors takes off!!!" but in the gui it always remained on the floor.

PS: I am aware of the work done by Huang and Sturm! I used their code until now for my PhD project but now I want to move to something more recent, and your repo is really interesting! Thank you for the contribution!

**Comment by nigno17** [comment] 2017-03-21 11:19
The problem is that in order to spawn multiple drones from code I changed a bit the drone plugins code (the one in the cvg_sim_gazebo_plugins folder). In particular one of the changes was to always add the name of the robot at the beginning of each topic name in the simple controller (on the other hand in the state controller it was enough to give relative names). For this reason you experienced that particular behavior. Now I'm working on a dead line and I don't have time to clean up the code. In the future I will correct it and make it consistent.

**Closed as completed** 2017-03-29 13:09 UTC
